/**
 * Evidence vocabulary.
 *
 * Authoro records who asserted what; it never flattens claims into a single
 * score or declares a work "human" or "AI". These constants are the shared
 * language for describing evidence, and every label names a concrete claim.
 */

import { z } from "zod";

/** Evidence classes, ordered from independently observed to self-reported. */
export const EVIDENCE_CLASSES = {
  "continuous-observed": {
    code: "A",
    label: "Continuous Observed Evidence",
    description: "The creation process was recorded continuously by an approved integration.",
  },
  "platform-history": {
    code: "B",
    label: "Platform History Evidence",
    description: "Revision history was imported from an editor or publishing platform.",
  },
  publisher: {
    code: "C",
    label: "Publisher Attestation",
    description: "A publisher confirmed the document, author, publication time or final content.",
  },
  identity: {
    code: "D",
    label: "Identity Attestation",
    description: "A third party confirmed something about a contributor's identity.",
  },
  ai: {
    code: "E",
    label: "AI Attestation",
    description: "An AI system or integration reported its own participation.",
  },
  self: {
    code: "F",
    label: "Author supplied",
    description: "Submitted directly by the creator, not independently observed.",
  },
} as const;

export type EvidenceClass = keyof typeof EVIDENCE_CLASSES;
export const evidenceClassSchema = z.enum(
  Object.keys(EVIDENCE_CLASSES) as [EvidenceClass, ...EvidenceClass[]],
);

/** Plain-English evidence states shown as separate badges; never combined into a score. */
export const EVIDENCE_STATES = {
  "author-attested": {
    label: "Author Attested",
    description:
      "The creator attested that the information in this record is true to the best of their knowledge.",
  },
  "creation-process-observed": {
    label: "Creation Process Observed",
    description: "An approved integration recorded evidence of the creation process.",
  },
  "platform-history-supplied": {
    label: "Platform History Supplied",
    description: "A platform supplied revision history for this work.",
  },
  "publication-confirmed": {
    label: "Publication Confirmed",
    description: "A publisher confirmed this exact version.",
  },
  "ai-participation-recorded": {
    label: "AI Participation Recorded",
    description: "A compatible AI provider submitted evidence of its contribution.",
  },
  "identity-verified": {
    label: "Identity Verified",
    description: "The account holder's identity was checked against identity documents.",
  },
  "final-artifact-verified": {
    label: "Final Artifact Verified",
    description: "A document checked against this record matches the registered fingerprint.",
  },
} as const;

export type EvidenceState = keyof typeof EVIDENCE_STATES;

/** How the creator describes the work's creation (V0 self-attestation). */
export const CREATION_METHODS = {
  manual: {
    label: "Fully manually composed",
    description: "I wrote or made this work myself without generative AI.",
  },
  "ai-assisted": {
    label: "AI-assisted",
    description: "Generative AI helped, e.g. with editing, feedback or research, but I composed the work.",
  },
  "ai-generated-sections": {
    label: "Contains AI-generated sections",
    description: "Some passages or elements were generated by AI.",
  },
  collaborative: {
    label: "Collaborative",
    description: "Other people contributed to this work.",
  },
  imported: {
    label: "Imported from another system",
    description: "This work was created elsewhere and brought into Authoro.",
  },
} as const;

export type CreationMethod = keyof typeof CREATION_METHODS;
export const creationMethodSchema = z.enum(
  Object.keys(CREATION_METHODS) as [CreationMethod, ...CreationMethod[]],
);

/** Specific ways AI was used, so disclosure is richer than a percentage. */
export const AI_USES = {
  brainstorming: "Brainstorming",
  outlining: "Outline generation",
  drafting: "Drafting passages",
  rewriting: "Rewriting",
  editing: "Grammar and copyediting",
  summarization: "Summarization",
  translation: "Translation",
  research: "Research",
  citations: "Citation assistance",
  media: "Images or other media",
} as const;

export type AiUse = keyof typeof AI_USES;
export const aiUseSchema = z.enum(Object.keys(AI_USES) as [AiUse, ...AiUse[]]);

const AI_METHODS: readonly CreationMethod[] = ["ai-assisted", "ai-generated-sections"];

/** The creator's self-attestation about how the work was made. Displayed as "Author supplied". */
export const creationDisclosureSchema = z
  .object({
    methods: z.array(creationMethodSchema).min(1).max(Object.keys(CREATION_METHODS).length),
    aiUses: z.array(aiUseSchema).max(Object.keys(AI_USES).length).default([]),
    aiTools: z.array(z.string().trim().min(1).max(80)).max(10).default([]),
    note: z.string().trim().max(2000).optional(),
  })
  .superRefine((disclosure, ctx) => {
    if (new Set(disclosure.methods).size !== disclosure.methods.length) {
      ctx.addIssue({ code: "custom", path: ["methods"], message: "Each method may be selected once." });
    }
    const usedAi = disclosure.methods.some((method) => AI_METHODS.includes(method));
    if (disclosure.methods.includes("manual") && usedAi) {
      ctx.addIssue({
        code: "custom",
        path: ["methods"],
        message: "A work cannot be both fully manually composed and AI-assisted or AI-generated.",
      });
    }
    if (!usedAi && (disclosure.aiUses.length > 0 || disclosure.aiTools.length > 0)) {
      ctx.addIssue({
        code: "custom",
        path: ["aiUses"],
        message: "AI uses and tools can only be listed when AI was involved.",
      });
    }
  });

export type CreationDisclosure = z.infer<typeof creationDisclosureSchema>;
